const countryProfileData = [
  {
    "countryName": "Germany",
    "euMember": true,
    "executiveSummary": [
      <div key="1" className="mt-2">The German political context for return policy in the period 2015 to 2022 is, on the one hand, primarily characterised by continuity despite a change of government in 2021. On the other hand, it is a repetition of the migration policymaking and rhetoric of the first half of the 1990s. The persistent trend is for migration and return policymaking to be grounded in domestic factors, particularly the steady rise of right-wing populist political voices and political groups that rally against immigration. Political rhetoric portrays immigrants as burdens on the social welfare system, contributing to the prioritization of deportation measures.</div>,
      <div key="2" className="mt-2">The German institutional framework for returns is highly complex due to multi-level governance with discretionary powers of the federal states and sub-national administrative actors (districts and municipalities) in the federal system. Decentralized enforcement by 16 states and their administrative bodies leads to challenges in uniform policy implementation. The Federal Ministry of the Interior plays a pivotal role in shaping return policies, with the Federal Office for Migration and Asylum (BAMF) serving as the operational entity. Return support services, such as counselling and financial assistance, exhibit variations across different federal states. Since 2015, the return governance framework has expanded to include intermediate coordination structures between the federal and state levels as well as inter-ministerial coordination at the federal level and between the state ministries of the interior.  Moreover, in this multi-level governance setup, the authority and discretionary powers of judges in district and administrative courts is noteworthy, as well as of the individual ‘decision-makers’ of the third-level Foreigners Authorities in that they have a special responsibility to make well-informed decisions.</div>,
      <div key="3" className="mt-2">Decentralized legal provisions and implementation of (supra)national requirements by multiple actors results in varying outcomes for migrants, and internal contradictions in policy execution create challenges in ensuring compliance during implementation. The influence of the Court of Justice of the European Union (CJEU) case-law significantly shapes return policies, adding layers of complexity to the legal framework. It should be acknowledged that various actors, in particular some political parties, have played an outstanding role in documenting or requesting data on returns through their parliamentary authority.</div>,
      <div key="4" className="mt-2">Nevertheless, there are several specific challenges in the German return regime including those related to the legislative, institutional, and international cooperation frameworks as well as issues in data collection, the enforcement, and political communication.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Sweden",
    "euMember": true,
    "executiveSummary": [
       <div key="1" className="mt-2">Sweden&apos;s return and readmission policies are shaped by both national and international  frameworks. The key legal instrument in Swedish migration law, including regarding matters  of return, is the 2006 Aliens Act which outline Sweden&apos;s specific procedures for returning  irregular migrants and those whose asylum claims are rejected. The Aliens Act is  supplemented by the 2006 Aliens Ordinance and several additional Acts and Ordinances, including the Administrative Act and the Administrative Procedures Act, as well as by EU law and international treaties and customary law in human rights and refugee law.</div>,
       <div key="2" className="mt-2">As also emphasized in GAPs-WP2 Sweden report, while return has been a priority at least on  paper for years, its urgency has intensified in recent years. This is evident from the Swedish  Migration Agency being directed by the Government to prioritise returns more than before, enhancing the efficiency of the return process and increasing the number of people actually  departing Sweden. As this report outlined, there appears to be a shift in focus from voluntary  to enforced returns, a development that aligns with the overall trend in Swedish migration policy towards greater restrictiveness since 2015, encapsulated by the principle &apos;no means no&apos;. This approach aims to ensure that Sweden does not deviate from the EU&apos;s minimum  standards for international protection, asylum procedures, reception conditions, and return measures. The 2022 Tidö Agreement&apos;s reforms further cement this stringent migration stance, reflecting what has been termed a &apos;paradigm shift&apos; in Swedish migration policy.</div>,
       <div key="3" className="mt-2">As an EU member state, Sweden adheres to the EU&apos;s common return policy, which emphasizes voluntary returns and reintegration in migrants&apos; home countries. It also promotes cooperation with third countries through readmission agreements. Several terms and definitions in the Return Directive or the Return Regulation1 have not been transformed into the Swedish Aliens Act or other Swedish legislation. As outlined in GAPs WP2-Sweden report, while amendments and revisions to Swedish legislation have indeed been enacted to incorporate the EU Return Directive and subsequent EU legislation on return into Swedish law, the Swedish government has, on numerous points, deemed such revisions unnecessary. The government has contended that existing legislation, principally the Aliens Act, already meets or surpasses the requirements of EU law, thereby obviating the need for additional measures to align Swedish law with EU directives on these matters. This includes several definitions listed in Article 3 of the Return Directive (such as &apos;irregular stay&apos; and &apos;assisted return&apos;), and the authorised exemption from applying the Return Directive under specific conditions outlined in Articles 2.2 a) and b).</div>,
       <div key="4" className="mt-2">The main governmental actors playing in return operations are Migration Agency (Migrationsverket) and the Police Authority (Polisen). To understand the Swedish system, it is essential to note that Swedish government agencies, including the Migration Agency and the Police Authority, are independent and largely autonomous in relation to the government. While the government has quite substantial scope for steering the operations of government agencies through annual appropriation directives and ordinances, by the appointment of top management, and through yearly monitoring and evaluations, the government has no powers to intervene in an agency&apos;s decisions in specific matters relating to the application of the law or the due exercise of its authority.2 Ministerial rule is in other words not allowed in Sweden.</div>,

       <div key="5" className="mt-2">The regulations about regular procedures for issuing return decisions and their consequences, including re-entry bans and voluntary deportation to Sweden, are primarily established in the Aliens Act and the Act (2022:700) Concerning Special Control of Certain Aliens. The latter Act addresses aliens considered to pose threats to national security. The Migration Agency has the authority to issue expulsion or removal and deportation-related decisions (Chapter 12, Section 14 and Chapter 8, Section 17), which may be appealed to the Migration Court (Chapter 14).3 The Police Authority can also, under certain circumstances, issue such decisions (Chapter 12, Section 14 and Chapter 8, Section 17), which may be appealed to the Migration Agency or a Migration Court (Chapter 14). In addition, decisions regarding expulsion due to criminal activity fall under the jurisdiction of the court responsible for the criminal case (Aliens Act, Chapter 8a, Section 10).</div>,
       <div key="6" className="mt-2">The Aliens Act also defines the area of responsibility of the Police Authority concerning the enforcement of expulsion and deportation decisions. This responsibility encompasses the execution of the Police Authority&apos;s expulsion and deportation decisions and court decisions for deportation due to criminal activities (Aliens Act, Chapter 12, Section 14). Additionally, it involves enforcing a decision of expulsion and deportation if the alien, after the decision has been enforced once, is found to have returned to Sweden (Chapter 12, Section 23). The Aliens Act, Chapter 8, specifies the various grounds for expulsion and deportation, stating that an alien lacking the necessary permit to stay in Sweden should be expelled or deported, while Chapter 12 details the different aspects of enforcement of expulsion and deportation decisions. For instance, crime or suspected criminality according to the Terrorist Crimes Act (2022:666) and considerations for Sweden&apos;s security that can be found in the Act (2022:700) on Special Control of Certain Aliens are stated as grounds for expulsion in the Aliens Act (Chapter 8, Section 1, Sub-Sections 1, 2 and 3). The Security Service enforces expulsion and deportation decisions related to security cases as specified in the Aliens Act (Chapter 12, Section 14) and defined in it (Chapter 1, Section 7). </div>,
       <div key="7" className="mt-2">The Aliens Act outlines the circumstances under which decisions on immediate enforcement can be implemented (Chapter 8, Section 19) and provides instructions for enforcement procedures (Chapter 8, Section 20). It also details when a decision on deportation or expulsion shall be considered executed (Chapter 12, Sections 21 and 22) and when enforcement of a decision has not ceased or is still applicable (Chapter 12, Section 23).</div>,
       <div key="8" className="mt-2">Sweden entered into 15 bilateral readmission agreements with various countries, both within and outside the EU, starting with Germany in 1956, as indicated by the schedule in an official document4 provided through communication with the Migration Agency. These countries include Iraq, Bulgaria, Cyprus, Estonia, France, Kosovo, Croatia, Estonia, Latvia, Lithuania, Romania, Switzerland, Germany, and Vietnam. Furthermore, from 2008 to 2022, Sweden has been a party to 18 EU and bilateral agreements, extending to countries such as Ukraine, Turkey, Sri Lanka, Serbia, Russia, Pakistan, Montenegro, Moldova, North Macedonia, Macao, Cape Verde, Hong Kong, Georgia, Bosnia, Belarus, Azerbaijan, Armenia, and Albania</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": false,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Greece",
    "euMember": true,
    "executiveSummary": [
      <div key="1" className="mt-2">Greece has a long history of (formal, informal and irregular) return migration policies and practices that have taken different forms depending on the political and socioeconomic context, including forced returns, deportations, push backs, spontaneous returns, and assisted voluntary returns. Since 2015, a number of developments foregrounded specific return procedures and practices, such as the EU-Turkey Statement and the increasing number of land and sea pushbacks (as reported/evidenced especially after the events in the Greek-Turkish border region of Evros in 2020). More recently, further institutionalisation of returns can be observed with the establishment of the Directorate of Returns and Withdrawals in 2020 and the position of a National Coordinator of Returns in late 2023 within the Ministry of Migration and Asylum (MMA).</div>,

      <div key="2" className="mt-2">The analysis of the legal and institutional framework governing returns in Greece highlights a number of gaps in terms of legal certainty, consistency and guaranties. The legal framework is characterised by ambiguity, mainly due to preceding legal arrangements on ‘administrative expulsion’ that remain in force. Particularly, Law 3907/2011 which transposed the Return Directive 2008/115/EC into the Greek legislation and determines the operation of returns, coexists with Law 3386/2005 concerning the administrative expulsions of Third Country Nationals. An additional complexity also arises as regards the multiple national, supranational and international actors involved in returns.</div>,

      <div key="3" className="mt-2">While the responsibility to design and implement migration policy as a whole lies with the MMA, the police authorities also have wide legal competences in return migration governance, especially in what concerns administrative expulsions, return decisions, detention and the management of the detention system. Existing legal safeguards against return, as for example those applying to minors, pregnant women, crime victims etc., are implemented under the proviso that a TCN is not considered dangerous for national security reasons, something which is again decided by the police.</div>,

      <div key="4" className="mt-2">As a result, a number of inconsistencies emerge, including the fact that the respective state administration is often able to bypass the procedures of the Directive and apply the deportation procedures. This is the case, for example, with expulsion decisions issued against TCNs illegally entering Greece at the borders even if the TCNs subsequently apply for international protection and obtain a permit to stay in the country; something that raises issues of compatibility with Article 2 para. (2) (a) of the Return Directive</div>,
      <div key="5" className="mt-2">Furthermore, the implementation of return, in most of its forms, is usually closely linked to detention as detention is the rule rather than the exception when there is a decision for return or deportation. This becomes evident as administrative detention is used extensively, on the grounds of public order and national security reasons, in some cases solely on the grounds of illegal entry, and despite numerous reports evidencing that the existing detention conditions severely violate detainees’ rights and dignity.</div>,

      <div key="6" className="mt-2">Existing legal inconsistencies are accompanied by poor data availability on returns. Data inconsistencies exist among different data categories (e.g. between administrative procedures and actual enforcement of returns), different data sources and different terms used. These observations may partly point to shifts in systems of recording and reporting on data over the years, alongside (in)consistency between statistical and legal categories and (lack of) convergence with EU terminology.</div>,

      <div key="7" className="mt-2">Assisted Voluntary Return and Reintegration program run by IOM provides the ground for a more humane approach to return migration, even if the context in which it operates is one of coercion, as it also addresses migrants who have been issued with a return decision and even detainees. Nevertheless, it remains underfunded if compared to other types of forced removals, a choice that reveals the political priorities of the authorities in current return and – more generally – migration issues.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Poland",
    "euMember": true,
    "executiveSummary": [
      <div key="1" className="mt-2">This report concerns the legal, institutional, and infrastructure framework regarding the return proceedings from Poland for foreigners with an irregular status for 2015-2023.</div>,
      <div key="2" className="mt-2">Poland has very effective enforcement of return decisions (90%). The rights of foreigners were drastically limited since 2021, which began with the humanitarian crisis on the Polish-Belarusian border.</div>,
      <div key="3" className="mt-2">Analysis of the legal framework of the return proceedings shows incorrect implementation of the directive. The report discusses the relationship of EU law to Polish law, Poland’s compliance with EU law and the implementation of judgments of European and international tribunals. Included also is a reference to cooperation between national institutions and organizations, as well as international cooperation. The practical knowledge of the report’s authors allows them to identify compliance with migrants’ rights.</div>,
      <div key="4" className="mt-2">The directive was implemented incompletely in 2013. Most mandatory changes to the law have been taken into account. Optional solutions improving the foreigner’s situation were omitted. For example, the possibility of waiving the entry ban in the return decision. Due to changes in the Act on Foreigners, since 2023 the Border Guard is the only body that deals comprehensively with return proceedings, which raises doubts as to the correctness of decision control in appeal proceedings and independence between first- and second-instance bodies. Foreigners do not have access to free public legal aid except for regular legal help provided by organizations supporting migrants. There is a lack of effective monitoring of the return operations, with monitoring of the independent body.</div>,
      <div key="5" className="mt-2">This report notes the biggest gaps as:</div>,
      <div key="6" className="mt-2">- improper implementation of the Return Directive through, among others, not providing procedural safeguards and access to free legal assistance;</div>,
      <div key="7" className="mt-2">- establishing the Border Guard as the only body conducting return obligation proceedings, both in the first and second instances, shortening the period for filing an appeal, and abolishing the suspensive effect of filing a complaint to court;</div>,
      <div key="8" className="mt-2">- lack of qualified guardians in return proceedings concerning unaccompanied minors;</div>,
      <div key="9" className="mt-2">- carrying out pushbacks, which have intensified since 2021 in connection with the humanitarian crisis on the Polish-Belarusian border. Despite numerous ECtHR judgments, pushbacks are carried out;</div>,
      <div key="10" className="mt-2">- automated use of detention, including the detention of children and the possibility of long-term detention;</div>,
      <div key="11" className="mt-2">- failure to ensure sufficient transparency in monitoring the implementation of return decisions, in particular by preventing the Ombudsman from monitoring.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": false,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Netherlands",
    "euMember": true,
    "executiveSummary": [
      <div key="1" className="mt-2">In the last two decades, the Netherlands has showed increased interest in migration enforcement. In this context questions of assisted and coerced return gained more significance over years, and has become a policy priority since 2018. The datafication of returns is part of this policy prioritization. Yet, researchers should be careful in reproducing these data as it is part of the legitimization of actual return policies. Considering the data, the number of third country nationals with a return order in the Netherlands vary between 15740 and 25310 in the last 10 years. According to the Dutch Authorities, roughly 2/3 of those returns that are considered ‘proven returns’ (aantoonbaar vertrek) can be considered voluntary returns (zelfstandig vertrek) and 1/3 can be considered coerced returns (Ministry of Justice and Security 2023, p. 113).</div>,
      <div key="2" className="mt-2">The Dutch approach to assisted and voluntary returns can be seen as a ‘carrot and stick’ approach (Ebrahim & Strik 2024). Those migrants who cooperate with their return processes are offered shelter and basic services, those who do not cooperate are excluded. The institutional landscape of return migration has become increasingly complex, with more and more bilateral agreements as well as more actors involved in return migration practices.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Turkey",
    "euMember": false,
    "executiveSummary": [
      <div key="1" className="mt-2">Turkey has historically been a crossroads between continents, serving as both a destination and a transit country for migrants and refugees. Its geopolitical position, bordering the European Union (EU) to the west and conflict zones to the south and east, has placed it at the centre of migration flows, particularly following the Syrian Civil War crisis in 2011 and the mass migration from this country. This position has compelled Turkey to significantly adapt and reformulate its migration and asylum policies over the last decade.</div>,

      <div key="2" className="mt-2">Turkey’s approach to return migration policy involves several key elements, encompassing legal frameworks, international cooperation, and specific programmes aimed at facilitating the return of migrants to their countries of origin. Understanding how Turkey enforces and formulates its return policies requires examining these components in detail.</div>,

      <div key="3" className="mt-2">Legal and Regulatory Framework: Turkey enforces return migration through a legal and regulatory framework aligned with national laws and international agreements. The Law on Foreigners and International Protection (LFIP) is a cornerstone, setting out the procedures and conditions for returning foreigners in Turkey who are found to be staying irregularly or may not qualify for international protection. The LFIP outlines procedures for deportation, voluntary return, and the rights and obligations of migrants and refugees within Turkish territory.</div>,

      <div key="4" className="mt-2">Readmission Agreements: Turkey has entered into readmission agreements with several countries and the European Union (EU). These agreements are crucial for enforcing return policies, as they outline the mutual responsibilities and mechanisms for the return of individuals residing irregularly in the territories of the signatory parties. In addition, Turkey has a bilateral agreement-like political document, the EU-Turkey Statement, which has articles related to return and readmission.</div>,

      <div key="5" className="mt-2">Cooperation with International Organizations: Turkey collaborates with international organisations, such as the International Organization for Migration (IOM), the United Nations High Commissioner for Refugees (UNHCR), and the International Centre for Migration Policy Development (ICMPD) to ensure the humane and orderly return of migrants. These collaborations often include assistance programs that support voluntary return and reintegration into the country of origin. Operational enforcement involves coordination with international bodies to ensure that returns are conducted in line with international refugee protection standards.</div>,

      <div key="6" className="mt-2">Regarding formulating return policies in Turkey, the policy development process involves a multi-stakeholder approach, including governmental bodies, non-governmental organisations (NGOs), international partners, and civil society. This collaborative process ensures that return policies are comprehensive, considering return migration’s legal, social, and humanitarian aspects.</div>,

      <div key="7" className="mt-2">Turkey’s return policies are developed in alignment with international standards and obligations. This includes adherence to principles of non-refoulement, human rights considerations, and ensuring the dignity and safety of migrants throughout the return process. However, the preliminary fieldwork findings in Turkey at the meso and micro levels reflected that alignment with international standards has some problematic dimensions.</div>,

      <div key="8" className="mt-2">A significant aspect of Turkey’s return policy formulation is the emphasis on voluntary return programs. These programs are designed to encourage a safe and dignified return for migrants who wish to go back to their countries of origin, often including support for reintegration efforts.</div>,

      <div key="9" className="mt-2">In addition, integration with broader migration management policies is critical, which ensures that return policies are part of a holistic approach to migration, addressing issues such as irregular migration, trafficking in persons, and asylum procedures.</div>,

      <div key="10" className="mt-2">Turkey’s return migration policies are shaped by a combination of domestic priorities and international cooperation, aiming to manage return migration in a way that respects the rights of migrants while meeting the country’s regulatory and security needs. These policies are subject to ongoing evaluation and adaptation, reflecting changes in migration flows, international agreements, and the broader geopolitical context.</div>,

      <div key="11" className="mt-2">Turkey enforces return migration through a combination of bilateral agreements, notably with the EU, and internal policies that manage and sometimes restrict the movements of refugees and migrants within its borders. The EU-Turkey Statement of 2016 is a pivotal point in understanding Turkey’s approach to return migration. This Statement, aimed at stemming the flow of irregular migration to Europe, essentially positioned Turkey as a gatekeeper, reducing the number of arrivals in Greece, which continued with significantly lower numbers in the subsequent years and ended as of March 2020 with COVID-19. The agreement not only aimed to decrease irregular migration but also included provisions for returning migrants not eligible for asylum in the EU back to Turkey in exchange for financial aid and other political incentives for Turkey. Despite the criticisms regarding its humanitarian implications, the deal has been considered effective in reducing irregular arrivals to Europe and has shaped future European migration diplomacy, including other bilateral agreements to manage migration flows. The renewal of the Statement, with the EU and Turkey having different demands for a new consensus, has been on the table for a long time. This political agreement, which has not been in effect since March 2020, is expected to be renewed in May 2024.</div>,

      <div key="12" className="mt-2">Turkey’s formulation of return policies is influenced by its strategic geopolitical position, the externalisation of EU migration policies, and its own national interests. The country transitioned from governmental neglect towards migration in the early 1990s to becoming an active participant in international migration governance, influenced significantly by EU pressure and assistance. This has led to the adoption of various legal and administrative measures aimed at managing and controlling migration, including the policing of unauthorised migration flows. Turkey’s migration governance has evolved into a technocratic regime, focusing on the legal infrastructure necessary to manage migration effectively and align with international norms, albeit with continued emphasis on controlling and limiting the influx of migrants and refugees. This approach balances humanitarian considerations and the practical realities of managing large-scale migration flows influenced by external pressures and internal policy goals.</div>,

      <div key="13" className="mt-2">The external dimensions of EU border policies have directly impacted the securitisation of irregular migration in Turkey, fostering a technocratic functioning of migration governance outside European borders. This externalisation has led to the construction of migrants as&apos;illegal subjects&apos; contributing to their inclusion in the domestic labour market under subordinate conditions. Turkey’s policies thus reflect a complex interplay between control and humanitarian intervention, shaped by external influences and its policy objectives regarding migration management.</div>,

      <div key="14" className="mt-2">These dynamics indicate that Turkey’s enforcement of return migration and its policy formulation are deeply intertwined with broader regional migration governance frameworks, particularly those driven by the European Union. They are subject to the changing political and social landscapes in which they operate. The timeline from 2019 to 2023, focusing on the most recent developments, highlights Turkey’s evolving return migration policy amid significant geopolitical, social, and health challenges. Recent years have seen Turkey announce plans for voluntary returns of Syrians to &apos;safe zones&apos; in northern Syria, reflecting a strategic approach to managing refugee populations in coordination with military operations such as Operation Euphrates Shield and Operation Olive Branch. The period also witnessed a border migration crisis with Greece, influenced by broader EU-Turkey negotiations on migration management. Amidst the COVID-19 pandemic, Turkey introduced measures such as the National Assisted Voluntary Return and Reintegration (N-AVRR) program and regulations to support refugee employment and voluntary returns. By 2023, discussions with the EU aimed at updating the 2016 Statement indicate a continued emphasis on international cooperation, while domestic policies show a shift towards the securitisation of migration, reflecting its increased politicisation during presidential elections. This period demonstrates Turkey’s multifaceted approach to migration, balancing international agreements, domestic policy adjustments, and security concerns.</div>,

      <div key="15" className="mt-2">Based on Turkey’s legal framework and practical applications, four types of returns are observed: pushbacks, forced returns, assisted returns and spontaneous returns. Regarding the pushbacks, the Turkey-Greece sea and land and Turkey-Bulgaria land borders are critical on the west; Turkey-Iran and Turkey-Syria land borders represent the east and south. Even though there are rare issues at the western border, such as Turkey’s February-March 2020 Turkey-Greece land border development, most of them on that side were mainly done by Greece. On the other hand, Turkey has pushback at the eastern borders, particularly the Turkey-Iran border. In terms of forced returns, administrative detention for returning and deportation exists, but Turkey also has readmission agreements and similar political collaboration pacts like the EU-Turkey Statement. Turkey also has two main assisted voluntary return programmes supported by IOM and ICPMD (the national programme is supported), particularly for non-Syrians. Finally, there are also &apos;spontaneous returns&apos;, although not highly representative, that are not supported and are based on individual decisions. The main legal framework exists for forced returns and assisted voluntary returns. However, due to regularisation deprivation, criminalisation practices have become increasingly more observable since 2019. However, in particular, in 2023, it has been stated that the fine line between forced and voluntary migration is becoming blurred, mainly according to the initial findings of fieldwork. Cases have been described where the consent of migrants in assisted voluntary returns, supported by meso-level actors and migrants themselves, becomes controversial.</div>,

      <div key="16" className="mt-2">Turkey’s return migration policies illustrate the complex interplay between national interests, international pressures, and humanitarian obligations. As Turkey continues to navigate its role as a key actor in regional migration governance, future policies must balance these often-competing priorities. Academically, this necessitates ongoing research to critically evaluate the impact of these policies on migrant rights, regional stability, and the evolving nature of international migration governance.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Iraq",
    "euMember": false,
    "executiveSummary": [
        <div key="1" className="mt-2">By: William Warda</div>, 
<div key="2" className="mt-2">The purpose of this report is to consolidate all plans, programs, and policies that Iraq possesses concerning migration, return, and asylum. The report aims to collect, organize, and document data and statistics, including relevant laws, regulations, and strategies. It also seeks to monitor the implemented orders and rulings that enhance the management of return migration and re-admission, making them easily accessible for studies on the governance of migration return, and facilitating their review and use in other research studies and reports. This may also contribute to their future development.</div>,
<div key="3" className="mt-2">Given that Iraq is a point of origin, transit, and destination for migrants and refugees, the patterns of migration in the country are diverse. Consequently, the Iraqi government has had to manage return and re-admission from multiple angles, particularly because Iraq receives not only voluntary and forced return requests but must also consider rights-based approaches from the perspective of host countries.</div>,
<div key="4" className="mt-2">The Iraqi research team has worked diligently in this report to assess Iraq’s readiness and ongoing efforts in this area, including relevant laws and regulations, available data and statistics, national strategies, and the key actors and stakeholders at both the national and international levels involved in managing the return process and their roles.</div>, 
<div key="5" className="mt-2">The team utilized fieldwork, including interviews and roundtable meetings with stakeholders, and participated in seminars and conferences during the research period. Based on these efforts, the report has documented, to the extent possible, most of the data, decisions, policies, and strategies that Iraq is working on regarding migration return, migration, and asylum.</div>,
<div key="6" className="mt-2">The report indicates that Iraq has taken serious steps towards enhancing the governance of migration return and re-admission since the launch of its national migration management strategy. On this basis, the Iraqi government has started improving its civil registration system to facilitate access to legal identity, which is a step towards safely and orderly managing migration return in a rights-based manner.</div>, 
<div key="7" className="mt-2">While Iraq does not have a comprehensive law on migration and asylum, and its law is limited to the 1971 political asylum law, it adopts a human rights-based approach in dealing with migration and return issues. Iraq has signed eight out of nine international human rights treaties under international human rights law.</div>,
<div key="8" className="mt-2">As a supporter of the Global Compact for Migration, Iraq has shown leadership in the area of return and re-admission, especially given its progress in fulfilling its commitments, including the recent establishment of a national referral mechanism, enhanced cooperation on re-admission, and improved technical capacities regarding return operations.</div>,
<div key="9" className="mt-2">Despite this, some challenges remain. Iraq needs to adapt and align its laws, regulations, and policies with the spirit of the 2005 Constitution and its international obligations. Notably, Iraq has yet to sign the 1948 International Convention on Migrant Workers, the 1951 Refugee Convention, and its 1967 Protocol. The management of return and re-admission requires the involvement of a broad range of stakeholders at both national and international levels. Iraq can strengthen national coordination among actors involved in return, including governmental and non-governmental stakeholders, international actors, and civil society organizations. It should also adopt a clear and transparent migration diplomacy, openly publishing bilateral or multilateral agreements, and demonstrating flexibility in information exchange regarding return operations, providing statistics on returnees, and developing a rapid referral mechanism to the newly established national referral system.</div>,
<div key="10" className="mt-2">Despite the challenges in accessing information in Iraq, including the absence of a law guaranteeing access to information and the weak cooperation of official institutions in sharing information among themselves and with researchers, the Iraqi research team was able to incorporate the following materials into the return migration data repository:</div>, 
<div key="11" className="mt-2">1. Iraqi laws, regulations, and systems concerning migration, asylum, and return.</div>,
<div key="12" className="mt-2">2. Clarification of Iraq’s plans and strategies regarding migration and return and its response approach.</div>,
<div key="13" className="mt-2">3. Data and statistics on refugees in Iraq, return levels, and refugee patterns.</div>,
<div key="14" className="mt-2">4. Diagrams and charts illustrating the work and coordination of governmental and on-governmental institutions and other actors involved in migration return.</div>,
<div key="15" className="mt-2">5. The nature of the work of actors involved in return, whether before, during, or after the return.</div>, 
<div key="16" className="mt-2">The details of these materials, laws, rulings, and various regulations for this report were gathered from available literature, selected data, statistics, and policies from some sources that preferred to remain anonymous. Some information was provided to the research team through interviews and meetings with stakeholders, as well as from reports and documents from international organizations.</div>
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": false,
    "actorReturnDiagram": false
  },
  {
    "countryName": "Jordan",
    "euMember": false,
    "executiveSummary": "",
    "returnPolicyTimeline": false,
    "returnFlowChart": false,
    "actorReturnDiagram": false
  },
  {
    "countryName": "Afghanistan",
    "euMember": false,
    "executiveSummary": [
      "For the majority of Afghan migration is a panacea for all socio-political and economic ills of the society.  In other words, people perceive migration as the best coping mechanism against  the day-to-day livelihood challenges ranging from family conflicts, physical insecurity, political instability and socioeconomic hardships. For example, Ahmad, a returnee respondent from Mazar-e Sharif who left Afghanistan in 2018, found out-migration as the best solution against the life threats caused by a conflict with powerful figures in his locality. Similarly, for Fawad, a returnee who left Afghanistan for Germany in 2019, out-migration was a life-saving strategy to escape assassination attempts, in one of which his brother-in-law lost his life. Lack of or absence of reliable and trustworthy legal institutions and functioning safeguard systems, particularly in rural areas force Afghans to opt out-migration as a life-saving mechanism to overcome security challenges that they face in their routine day-to-day activities.",
      "Data from the field observations indicate that a range of psychological factors  (some may have root in trauma felt in early childhood due to war and its associated challenges) from feeling inconsequential, inability to attract family and social attraction, depression, post traumatic syndrome (PTSD), anxiety, and sentiments of proving oneself capable of achieving success in life have significant contribution in navigating aspiration for migration as a life saving coping mechanism. Lack of economic opportunity, lack or no social services, and ambiguities surrounding political situations have left Afghan families with no prospects for the future. Thus, for Afghan families too migration is perceived as an ideal life-saving strategy to (i) protect children from physical and psychological harm and (ii) secure economic insurance for the families."
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Nigeria",
    "euMember": false,
    "executiveSummary": "",
    "returnPolicyTimeline": false,
    "returnFlowChart": false,
    "actorReturnDiagram": false
  },
  {
    "countryName": "Morocco",
    "euMember": false,
    "executiveSummary": [
      "Context: Return migration is a critical aspect of migration dynamics. Positioned on the two main routes of irregular migration to Europe, Morocco serves as a transit point for migrants traveling through the Western Mediterranean route, linking Morocco with the Spanish mainland, the Balearic Islands, andthe two occupied Moroccan enclaves of Ceuta and Melilla, as well as the Western African Atlantic route connecting the coasts of West African countries to the Canary Islands. This geographical significance necessitates reinforced border control, contributing to continuous arrests and pushbacks by national authorities.",
      "With an estimate of more than 100,000 irregular migrants living in its territory, Morocco faces significant challenges in managing migration flows, including return to countries of origin, and protecting migrants&apos; rights. Additionally, Morocco is an essential partner for the EU in migration management, particularly in combating irregular migration and border control. Cooperation between the EU and Morocco is crucial for addressing common migration challenges and promoting regional development.",
      "Despite adopting progressive migration policies, including a ‘’New immigration policy’’ in 2013, the National Strategy for Immigration and Asylum (SNIA), Morocco still faces internal challenges in migration, including protecting migrants&apos; rights and integrating them into Moroccan society. Bridging these gaps and developing more effective approaches to return migration requires extensive research and collaboration among Moroccan authorities, civil society, international organizations, and development partners. This collaboration is essential to develop policies and programs that meet migrants&apos; needs and advocate for dignified and safe return migration.",
      "As a key member of the GAPs project, the case of Morocco is central to the studied migration dynamics. Its pivotal role in migration routes to Europe strengthens its involvement in proposing governance and cooperation models for return migration."
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Tunisia",
    "euMember": false,
    "executiveSummary": [
      "Placeholder paragraph 1",
      "Placeholder paragraph 2",
      "Placeholder paragraph 3"
    ],
    "returnPolicyTimeline": true,
    "returnFlowChart": true,
    "actorReturnDiagram": true
  },
  {
    "countryName": "Canada",
    "euMember": false,
    "executiveSummary": [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vehicula magna eget tellus consectetur, at fermentum sem consectetur. Phasellus tincidunt purus eu magna sagittis, nec tristique velit posuere. Nullam auctor sem nec justo venenatis, quis fermentum lorem consequat. Nulla facilisi. Donec in urna ac dui interdum venenatis. Sed auctor, ante quis convallis vestibulum, nunc ex consequat velit, nec convallis quam turpis a velit. Phasellus malesuada velit non odio ultrices, nec convallis sem suscipit.",
      "Fusce ullamcorper sapien et mauris dapibus feugiat. Sed interdum risus ac tellus aliquam, in luctus purus scelerisque. Nunc rutrum, mauris at convallis fermentum, sapien lacus iaculis libero, eu bibendum dui velit vel nisi. In vehicula tellus ac libero malesuada, vitae vulputate risus luctus. Proin nec ipsum ultricies, consequat enim non, consectetur libero. Pellentesque non gravida nulla.",
      "Maecenas ac est nec leo congue posuere. Vivamus eget ligula vitae mi interdum varius. Integer lacinia, nunc sit amet gravida convallis, ipsum purus pharetra diam, eget condimentum velit arcu nec justo. Nam ac tortor vitae nunc tincidunt fermentum. Suspendisse ut libero eu dolor congue placerat. Nulla facilisi. Cras molestie libero sed dolor fermentum, nec molestie enim varius."
    ],
    "returnPolicyTimeline": false,
    "returnFlowChart": false,
    "actorReturnDiagram": false
  },
  {
    "countryName": "United Kingdom",
    "euMember": false,
    "executiveSummary": "Executive Summary (Record ID 1700-1).xlsx",
    "returnPolicyTimeline": false,
    "returnFlowChart": false,
    "actorReturnDiagram": false
  }
]

export default countryProfileData